// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYR4hr98odneiXX0HZQGzDtWndPkdhzw',
    appId: '1:592034003051:web:1a3a4480ce9203dc02592e',
    messagingSenderId: '592034003051',
    projectId: 'gen-lang-client-0627362600',
    authDomain: 'gen-lang-client-0627362600.firebaseapp.com',
    storageBucket: 'gen-lang-client-0627362600.firebasestorage.app',
    measurementId: 'G-QMYVVL1GXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85sNNnkOwATsY0YHLXh4dxZ1PvvyzDfg',
    appId: '1:592034003051:android:53cb40e3f2baab9602592e',
    messagingSenderId: '592034003051',
    projectId: 'gen-lang-client-0627362600',
    storageBucket: 'gen-lang-client-0627362600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjpseIIaQgIbB0J2tl6MmKIAcCQGq_bQ',
    appId: '1:592034003051:ios:435118a25650fd1302592e',
    messagingSenderId: '592034003051',
    projectId: 'gen-lang-client-0627362600',
    storageBucket: 'gen-lang-client-0627362600.firebasestorage.app',
    iosBundleId: 'com.example.quickSpend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjpseIIaQgIbB0J2tl6MmKIAcCQGq_bQ',
    appId: '1:592034003051:ios:435118a25650fd1302592e',
    messagingSenderId: '592034003051',
    projectId: 'gen-lang-client-0627362600',
    storageBucket: 'gen-lang-client-0627362600.firebasestorage.app',
    iosBundleId: 'com.example.quickSpend',
  );
}
